- name: server Installation
  hosts: server1
  gather_facts: false   # Comment this to enable gather facts
  become: yes
  tasks:
        - name: Install software packages
          apt:
            name: "{{ item }}"
            state: present
          loop: "{{ package_list.split(',') }}"
