---

- name: Install nginx
  apt:
      name: nginx
      state: present
      update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"
